### ISSUE TITLE
Export Current status of joal in a text file

### ISSUE THREAD

**Issue by deadpansociety** [anthonyraymond/joal-ui#2]
Is there a way to get information(per torrent seed/leech & up-speed) of https://raw.githubusercontent.com/anthonyraymond/joal/master/readme-assets/webui-preview.png window as a text file? 

When there's a thousand of torrents running in joal, the webui is quite unresponsive for me. Webui crashes for large sum of torrents. It'd be helpful to have some alternative

**Comment by anthonyraymond** [comment]
Sort feature is close to be ready :)

![image](https://user-images.githubusercontent.com/7503585/57962522-dcf89c80-7917-11e9-9598-23511b8075e1.png)


![image](https://user-images.githubusercontent.com/7503585/57962524-f0a40300-7917-11e9-9c77-b01cd75c15b5.png)


But the pageable table is not yet ready

**Comment by anthonyraymond** [comment]
@deadpansociety Should be available in the next few weeks

![image](https://user-images.githubusercontent.com/7503585/58676122-6ae07880-8357-11e9-968a-fef37dbc2d73.png)

**Comment by anthonyraymond** [comment]
@deadpansociety The new version of joal is now available. With search bar and sort buttons (you can update to 2.1.16)
